config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :activities
  
  get '/',
    to: 'activities#index',
    as: :activities_index
end

app/models/activity.rb
class Activity < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[ show edit update destroy ]

  # GET /activities or /activities.json
  def index
    @activities = Activity.all
    @activity = Activity.new
  end

  # GET /activities/1 or /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities or /activities.json
  def create
    @activity = Activity.new(activity_params)
    respond_to do |format|
      if @activity.save
        flash[:msg] = "Atividade criada com sucesso alerta."
        format.html { redirect_to activities_index_url, notice: "Atividade criada com sucesso." }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      flash[:msg] = "Atividade destruída com sucesso alerta."
      format.html { redirect_to activities_url, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:name, :description, :date)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<% if flash[:msg] %>
    <script>
        alert('<%= flash[:msg] %>');
    </script>
<% end %>

<div id="form-create-activity">
    <%= form_for @activity do |a| %>
        <h3> Criar nova atividade </h3>
        <%= a.text_field :name %>
        <%= a.text_field :date, 
            type: "date" %>
        <%= a.text_area :description, 
            style: "resize: none" %>

        <%= a.submit 'Criar Atividade' %>
        
    <% end %>
</div>
<table id="list-activities">
<%= @activities.find_each do |activity| %>
  <tr class="activity-item">
      <td> <%= activity.name %> </td>
      <td> <%= activity.date.strftime("%d/%m/%Y") %> </td>
      <td> <%= activity.description %> </td>
  
      <td>
          <%= button_to 'Apagar', 
              activity, 
              method: :delete, 
              :onclick => "return confirm('Tem certeza que quer deletar esta atividade?')" %>
      </td>
  </tr>
  <% end %>
</table>

<br>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @activity.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @activity.date %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AplicacaoAtividadeRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section id="menu">
      <%= render "shared/menu" %>
    </section>

    <section id="content">
      <%= yield %>
    </section>

    <section id="footer">
      <footer>
        <%= render "shared/footer" %>
      </footer>
    </section>

  </body>
</html>

app/views/shared/_footer.html.erb
<div>
    <p>Esse é o footer</p>
</div>

app/views/shared/_menu.html.erb
<h2><a href="/">Agenda</a></h2>